services:
  - type: web
    name: dmify-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    domains:
      - dmify-app-1.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    envVars:
      - key: NODE_ENV
        value: production
